### ISSUE TITLE
Remove gossipConnection property from clientInfo

### ISSUE THREAD

**Issue by jorgebay** [barcostreams/barco#120]
Initially, we used the status of a connection to keep track of the status of a peer broker.
We've since started using another approach but we didn't remove the property and the usage of the property.

To Remove:
-  [Calls to `Store()](https://github.com/barcostreams/barco/blob/v0.5.1/internal/interbroker/gossip_client.go#L220-L221)
- [The property and field](https://github.com/barcostreams/barco/blob/v0.5.1/internal/interbroker/gossip_client.go#L182)
- [`NewFailedConnection()` function](https://github.com/barcostreams/barco/blob/cdb02d5b446eb379520a8a6d587a5ec75210b5f2/internal/types/tracked_connection.go#L39)

**Comment by Mihai22125** [comment]
Hi @jorgebay, I'd like to work on this item. Can you assign it to me please?

**Comment by jorgebay** [comment]
@Mihai22125 done!
