### ISSUE TITLE
Barco pods failing in OpenShift 4

### ISSUE THREAD

**Issue by rmarting** [barcostreams/barco#18]
I am testing Barco in OpenShift version 4.11 (Kubernetes version v1.24.0+4f0dd4d) but the Barco pods are not starting successfully. Following the installation (where I found some warnings reported here #17), the pods are in the following state:

```shell
$ oc get pod
NAME      READY   STATUS             RESTARTS        AGE
barco-0   0/1     CrashLoopBackOff   7 (21s ago)     11m
barco-1   0/1     Error              7 (5m21s ago)   11m
```

Checking the pod logs :

```shell
$ oc logs -f barco-0
{"level":"info","time":"2022-09-19T06:31:55Z","message":"Starting Barco"}
{"level":"info","time":"2022-09-19T06:31:55Z","message":"Using home dir as /var/lib/barco"}
{"level":"info","time":"2022-09-19T06:31:55Z","message":"Initializing local db from /var/lib/barco/data/local.db"}
{"level":"fatal","error":"unable to open database file: no such file or directory","time":"2022-09-19T06:31:55Z","message":"Exiting"}
```

**Steps to reproduce**

1. Use OpenShift Local to start a local instance of OpenShift (Instructions [here](https://developers.redhat.com/products/openshift-local/overview))
2. Start it
3. Execute commands described in [Installing Barco Streams on Kubernetes](https://github.com/barcostreams/barco/blob/main/docs/install/KUBERNETES.md) page
4. Check pod's status

**Comment by jorgebay** [comment]
Good stuff! Thanks for trying it out on OC.

OpenShift should be supported out of the box, I'll try it out and see how we can support running as non-root and/or supporting OC security best practices. Any pointers would be appreciated.

**Comment by rmarting** [comment]
OpenShift by default doesn't allow running containers with _root_ privileges. Maybe this [blog post](https://developers.redhat.com/blog/2020/10/26/adapting-docker-and-kubernetes-containers-to-run-on-red-hat-openshift-container-platform#group_ownership_and_file_permission) could help you to address it.

**Comment by rmarting** [comment]
Confirmed that now it is running successfully in my OCP 4.11 cluster:

```shell
❯ oc get pod -n streams
NAME      READY   STATUS    RESTARTS   AGE
barco-0   1/1     Running   0          48s
barco-1   1/1     Running   0          43s
barco-2   1/1     Running   0          39s
```

**Comment by jorgebay** [comment]
Great! thanks @rmarting !!
