### ISSUE TITLE
Mixed casing conventions for the REST API

### ISSUE THREAD

**Issue by jorgebay** [barcostreams/barco#95]
We recently introduced `consumer_id` querystring parameter which uses snake case but the API uses camelCase...

We should change it to `consumerId` on `v0.5.0`, while still supporting the snake case version until `v0.7.0`.

**Comment by akisan13245** [comment]
i think camelcase is not as good as snakecase ,because snakecase can be more readable and multi-user but if api only supports camel it's ok,you can still use camelcase on 0.7.0 for your api

**Comment by jorgebay** [comment]
@akisan13245 I agree, I think snake case is more readable and newer projects tend to go in the direction of snake case for json messages. The problem is that [all the messages use camelCase](https://github.com/barcostreams/barco/blob/41ead7a3b5b10511e8d9099fcd768fc2afc62564/internal/consuming/models.go#L118-L139) and it would be a huge (breaking) change to change it.

Hopefully, unifying the naming convention towards one (camelCase) is better than having mixed ones :)
