### ISSUE TITLE
duplicate column name when container restarts

### ISSUE THREAD

**Issue by helmutkemper** [barcostreams/barco#96]
When the container restarts, the `ALTER TABLE ...` command generates the error: `duplicate column name: cluster_size`

**Comment by jorgebay** [comment]
Nice findings @helmutkemper !

This issue is on `master` but not on `v0.4.1`, I'll add it to the upcoming `v0.5.0` release, per our discussions, assign it to you :)

**Comment by jorgebay** [comment]
We could add a test to cover this issue [here](https://github.com/barcostreams/barco/blob/main/internal/localdb/queries_test.go#L22).

Something like:

```golang
Describe("Init()", func() {
	It("should support running multiple times", func() {
		client := NewClient(&testConfig{}).(*client)
		err := client.Init()
		Expect(client.Init()).NotTo(HaveOccurred())

		// Running a second time
		err = client.Init()
		Expect(err).NotTo(HaveOccurred())
	})
})
```
